# Setup
title: CERN Vidyo Team on Github
email: vc-team@cern.ch
tagline:      Public Github repository for CERN Vidyo team projects
baseurl:      ""
paginate:     1

# About/contact
author:
  name:       CERN VC Team
  url:        http://vidyowebrtc.web.cern.ch

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown